"""Reproducible bytes for generated spreadsheets; manual attachments stay intact."""
from io import BytesIO
from zipfile import ZipFile, ZipInfo, ZIP_DEFLATED
from lxml import etree


def workbook_bytes(book):
    """Remove creation-time variance only from files generated by NuRus.

    Excel/Outlook duplicate detection still hashes every real byte, including
    edits to generated attachments. No semantic shortcut applies to user files.
    """
    raw = BytesIO()
    book.save(raw)
    result = BytesIO()
    with ZipFile(raw) as source, ZipFile(result, 'w', ZIP_DEFLATED) as target:
        for name in sorted(source.namelist()):
            content = source.read(name)
            if name == 'docProps/core.xml':
                root = etree.fromstring(content)
                for tag in ('created', 'modified'):
                    node = root.find('{http://purl.org/dc/terms/}' + tag)
                    if node is not None:
                        node.text = '2000-01-01T00:00:00Z'
                content = etree.tostring(root)
            info = ZipInfo(name, date_time=(2000, 1, 1, 0, 0, 0))
            info.compress_type = ZIP_DEFLATED
            target.writestr(info, content)
    return result.getvalue()

